name: Build blog

on:
  push:
    branches:
      - master
      - build-pipeline # FIXME: just for dev / testing

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies & build
        run: |
          npx yarn
          npx yarn build
          
      - name: save build artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: _site/
          
  deploy:
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: build-artifact

      - name: Display structure of downloaded files
        run: ls -R
